# Generated by Django 3.1 on 2020-11-14 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='celular',
            name='foto',
            field=models.ImageField(default='', upload_to='Celulares'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celular',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('cantidad', models.IntegerField()),
                ('valorneto', models.IntegerField()),
                ('fecharecepcion', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='Accesorios')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
