# Generated by Django 3.1.2 on 2020-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celulares',
            name='color',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='celulares',
            name='marca',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='celulares',
            name='sistemaoperativo',
            field=models.TextField(max_length=100),
        ),
    ]
