# Generated by Django 3.1 on 2020-11-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='celular',
            name='color',
            field=models.CharField(max_length=200),
        ),
    ]
