# Generated by Django 3.1 on 2020-11-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celu', '0002_auto_20201110_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('cantidad', models.IntegerField()),
                ('valorneto', models.IntegerField()),
                ('foto', models.ImageField(upload_to='Producto')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='celular',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='celular',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='celular',
            name='fecharecepcion',
        ),
        migrations.RemoveField(
            model_name='celular',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='celular',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='celular',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='celular',
            name='valorneto',
        ),
        migrations.DeleteModel(
            name='Accesorios',
        ),
    ]
