# Generated by Django 3.1 on 2020-11-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0002_auto_20201115_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='celu.tipo'),
            preserve_default=False,
        ),
    ]
