# Generated by Django 3.1 on 2020-11-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0002_auto_20201109_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
