# Generated by Django 3.1 on 2020-11-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0003_auto_20201109_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='foto',
            field=models.ImageField(default='', upload_to='picture/celulares'),
            preserve_default=False,
        ),
    ]
