# Generated by Django 3.1 on 2020-11-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0003_auto_20201114_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Accesorio',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='celu.accesorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Celular',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='celu.celular'),
            preserve_default=False,
        ),
    ]
