# Generated by Django 3.1 on 2020-11-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0002_auto_20201110_1700'),
        ('celu', '0003_auto_20201103_1651'),
    ]

    operations = [
    ]
