# Generated by Django 3.1 on 2020-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0004_celular_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='foto',
            field=models.ImageField(upload_to='celu/picture/celulares'),
        ),
    ]
