# Generated by Django 3.1 on 2020-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0005_remove_producto_accesorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Accesorio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Celular',
        ),
        migrations.DeleteModel(
            name='Celular',
        ),
    ]
