# Generated by Django 3.1 on 2020-11-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0005_auto_20201109_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='foto',
            field=models.ImageField(upload_to='celu/static/picture/celulares'),
        ),
    ]
