# Generated by Django 3.1 on 2020-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0007_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sistemaoperativo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
