# Generated by Django 3.1 on 2020-11-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0008_auto_20201109_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='foto',
            field=models.ImageField(upload_to='static/picture/celulares'),
        ),
    ]
