# Generated by Django 3.1 on 2020-11-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0008_producto_sistemaoperativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
