# Generated by Django 3.1 on 2020-11-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0014_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Tipo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='celu.tipo'),
            preserve_default=False,
        ),
    ]
