# Generated by Django 3.1 on 2020-11-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0015_producto_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
