# Generated by Django 3.1 on 2020-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0017_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sistemaoperativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
