# Generated by Django 3.1 on 2020-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0018_auto_20201114_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
