# Generated by Django 3.1 on 2020-11-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0022_remove_producto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='Producto',
        ),
    ]
