# Generated by Django 3.1 on 2020-11-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0024_producto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='Tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='celu.tipo'),
            preserve_default=False,
        ),
    ]
