# Generated by Django 3.1 on 2020-11-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0025_auto_20201114_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(null=True)),
                ('CantidadCompras', models.IntegerField(null=True)),
            ],
        ),
    ]
