# Generated by Django 3.1 on 2020-11-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celu', '0028_auto_20201115_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='Detalle_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='celu.detalleproducto'),
            preserve_default=False,
        ),
    ]
