# Generated by Django 3.1 on 2020-12-05 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celu', '0030_auto_20201204_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='Cliente_id',
        ),
        migrations.AddField(
            model_name='carrito',
            name='Cliente_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
